"""followers

Revision ID: 20caeeed7a79
Revises: 9319b9a23ae5
Create Date: 2021-02-11 21:12:21.015989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20caeeed7a79'
down_revision = '9319b9a23ae5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
